version: '3'
services:
  # Spring Boot Application
  social-media-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/socials_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: damn
    networks:
      - my-network

  # PostgreSQL Database
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: socials_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: damn
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:

